import { Metadata } from "next";
import { ReactNode } from "react";
import LayoutClient from "./layout-client";

export const metadata: Metadata = {
    title: "mood swing",
    description: "Generated by create next app",
};

export default function Layout({ children }: { children: ReactNode }) {
    return (
        <LayoutClient>
            {children}
        </LayoutClient>
    );
}
