import { ReactNode } from "react";
import LayoutClient from "./layout-client";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: 'pay up!',
    description: 'Generated by create next app',
}

export default function Layout({ children }: { children: ReactNode }) {
    return (
        <LayoutClient>
            {children}
        </LayoutClient>
    );
}
